spring.application.name=backend
server.port=8080

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/landorshop}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:password}

spring.sql.init.mode=always

spring.sql.init.schema-locations[0]=classpath:db/migration/V1__create_tables.sql
spring.sql.init.schema-locations[1]=classpath:db/migration/V2__add_constraints.sql

spring.sql.init.data-locations[0]=classpath:db/seed/V100__seed_base_data.sql

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.resolve-lazily=false

# ???????? ????????? security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# ?????????? ??????????
logging.level.org.springframework.security=DEBUG
logging.level.com.example.backend=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.boot.model=TRACE

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

# ??? ??????? ????????
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

# Disable Docker
spring.docker.compose.enabled=false


#admin
admin.email=${ADMIN_EMAIL:}
admin.password=${ADMIN_PASSWORD:} 
admin.firstName=${ADMIN_FIRST_NAME:}
admin.lastName=${ADMIN_LAST_NAME:}
admin.phone=${ADMIN_PHONE:}