spring.application.name=backend
server.port=8080

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://db:5432/landorshop}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:password}

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/migration/V1__create_tables.sql,classpath:db/migration/V2__add_constraints.sql
spring.sql.init.data-locations=classpath:db/seed/V100__seed_base_data.sql

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

admin.email=${ADMIN_EMAIL:admin@landorshop.ru}
admin.password=${ADMIN_PASSWORD:ChangeMe123!}
admin.firstName=${ADMIN_FIRST_NAME:?????}
admin.lastName=${ADMIN_LAST_NAME:?????????}
admin.phone=${ADMIN_PHONE:+79991234567}


spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.resolve-lazily=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.com.example.backend=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

spring.docker.compose.enabled=false